name: lisa_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  get_it: ^7.2.0
  injectable: ^1.5.4
  dartz: ^0.10.1
  json_serializable: ^6.5.4

  flutter_riverpod: ^2.1.1
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1

  go_router: ^5.1.5
  easy_localization: ^3.0.1
  connectivity_plus: ^3.0.2


  firebase_core: 2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4


  flutter_svg: ^1.1.6

  app_authentication:
    path: packages/authentication

  app_ui:
    path: packages/app_ui

  atomic_ui:
    path: packages/atomic_ui

  lisa_bottom_bar:
    path: packages/lisa_bottom_bar



dependency_overrides:
  firebase_core_platform_interface: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  logger: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_flavorizr: ^2.1.5
  injectable_generator: ^1.5.4
  build_runner:
  lint: ^1.10.0


  freezed: null
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  import_sorter: ^4.6.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/vectors/

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    dev:
      app:
        name: "Lisa dev"

      android:
        applicationId: "olivier.lisa_app"
        firebase:
          config: ".firebase/dev/google-services.json"

      ios:
        bundleId: "olivier.lisa-app"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"

    prod:
      app:
        name: "Lisa"

      android:
        applicationId: "olivier.lisa_app"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "olivier.lisa_app"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"


# Generated by Spider
spider:
  generate_tests: true
  no_comments: true
  export: true
  use_part_of: true
  use_references_list: false
  package: generated
  groups:
    - class_name: Images
      sub_groups:
        - path: assets/images
          types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]
        - path: assets/vectors
          prefix: svg
          types: [ .svg ]

import_sorter:
  comments: false