name: app_authentication
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.0.2
  hooks_riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1

  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  google_sign_in: ^5.4.2

  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1



