name: app_authentication
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.1.1
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1

#
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  google_sign_in: ^5.4.2

  dartz: ^0.10.1
  json_serializable: ^6.5.4

  easy_localization: ^3.0.1
  flutter_secure_storage: ^6.0.0
  connectivity_plus: ^3.0.2

  firebase_auth_mocks: ^0.9.1
  json_annotation: ^4.7.0

dependency_overrides:
  firebase_core_platform_interface: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: null
  freezed_annotation: ^2.2.0
  build_runner:
  mockito: ^5.3.2
  state_notifier_test: ^0.0.9


flutter:

  assets:
    - assets/
    - assets/translations/
